### ISSUE TITLE
Makefile does not respect DESTDIR variable

### ISSUE THREAD

**Issue by mmokrejs** [gmarcais/yaggo#7]
Hi,
  it is common that Makefile.am rules respect $(DESTDIR) variable which value get preprended in front of $(PREFIX), so that files are installe din the desired place.

```
>>> Install yaggo-1.5.9 into /scratch/var/tmp/portage/dev-lang/yaggo-1.5.9/image/ category dev-lang
make -j2 DESTDIR=/scratch/var/tmp/portage/dev-lang/yaggo-1.5.9/image/ install 
ruby bin/create_yaggo_one_file ./yaggo
mkdir -p /usr/local/bin
mkdir -p /usr/local/share/doc/yaggo
 * ACCESS DENIED:  mkdir:        /usr/local/share
mkdir: cannot create directory '/usr/local/share': Permission denied
```

Fix is simple:

`sed -e 's/$(prefix)/$(DESTDIR)$(prefix)/g' -i Makefile`

**Comment by gmarcais** [comment]
The new version does just what you suggested. Thanks.

**Comment by mmokrejs** [comment]
There is still an issue with 1.5.10, see my comment about the commit.
